import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:member_app_v2/common/localization/language/en_US.dart';
import 'package:member_app_v2/data/shared_prefs/shared_prefs.dart';

class AppLocalization extends Translations {
  static Locale? get locale => getLocale();
  static const fallbackLocale = Locale('en', 'US');

  static Locale getLocale() {
    switch (SharedPrefs.uiLanguageCode) {
      case "en":
        return const Locale('en', 'US');
      default:
        return const Locale('en', 'US');
    }
  }

  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': en_Us,
      };
}

enum TranslationKeys {
  appName,
  noTransactionFound,
  noVoucherFound,
  pullUpLoad,
  noMoreData,
  clickToRetry,
  skipIntro,
  createAccount,
  signInInsted,
  introTitle1,
  introTitle2,
  introTitle3,
  introSubtitle1,
  introSubtitle2,
  introSubtitle3,
  thankYou,
  verificationSuccessMessage,
  noInternetConnection,
  name,
  email,
  phoneNo,
  dateOfBirth,
  password,
  sendOtpCode,
  iAcceptThe,
  termCondition,
  and,
  pdpNotice,
  recieveUpdate,
  contactUs,
  anytime,
  otpVerification,
  enterVerificationCodeHere,
  verifyNow,
  resendCode,
  enterValidPhoneNumberOtp,
  unableToProcessRequest,
  pleaseVerifyPhoneNumber,
  somethingWentWrong,
  tabHome,
  tabCategories,
  tabMembership,
  tabProfile,
  login,
  emailOrPhone,
  forgotYourPassword,
  signIn,
  enterValidEmailPhone,
  enterValidPassword,
  promotionCaption,
  promotionSubtitle,
  searchByKeyword,
  sortBy,
  filter,
  items,
  addToBag,
  itemAdded,
  reset,
  price,
  from,
  to,
  size,
  selected,
  viewMoreOptions,
  color,
  applyFilter,
  noResultFor,
  refNo,
  otherOptions,
  quantity,
  productDescription,
  shippingDelivery,
  returnExchange,
  youMightLike,
  loyaltyPoints,
  membershipCard,
  addToAppleWallet,
  membershipManagement,
  claimRewards,
  myVouchers,
  viewTransactions,
  myWishlist,
  recentlyViewd,
  storeLocator,
  contactUsKiv,
  settings,
  termOfUse,
  privacyPolicy,
  support,
  profileManagement,
  shopNow,
  newRelease,
  discoverNewProduct,
  bestSelling,
  wontMissOffer,
  readyToWear,
  ourCuratedProduct,
  history,
  searchHistory,

  brand,
  categories,
  clearAll,
  clearAllRetry,
  shipping,
  calculatedAtCheckout,
  welcomeTo,
  family,
  useCode,
  userProfile,
  accountManagement,
  payment,
  editProfile,
  accountSettings,
  accountSettingsTitle,
  changePassword,
  changePasswordTitle,
  paymentMethod,
  choosePaymentMethod,
  changeAddress,
  editAddress,
  addAddress,
  saveInformation,
  addNewAddress,
  makeDefaultAddress,
  onlineBanking,
  creditDebitCard,
  payLaterByGrab,
  shopBack,
  processingPayment,
  paymentSuccessful,
  thankYouForShoppingWithUs,
  paymentFailed,
  wouldYouLikeToTryAgain,
  backToHomepage,
  loginSuccessMessage,
  alreadyHaveAccount,
  notHaveAccount,
  cart,
  checkoutItems,
  checkout,
  products,
  shippingDetails,
  deliveryAddress,
  shippingOptions,
  standardDelivery,
  vouchers,
  noVouchersSelected,
  total,
  proceedToPayment,
  receivedBy,
  cartEmptyMessage,
  instantDelivery,
  chooseShippingOptions,
  cartTitle,
  logout,
  logoutConfirmMessage,
  selectSizeAndColor,
  browseFullCollection,
  itemAddedToCart,
  itemAddedToWishlist,
  itemRemoveFromWishlist,
  subtotal,
  discountAmount,
  tax,
  noShippingMethodSelected,
  noAddressSelected,
  noPaymentMethodSelected,
  orders,
  orderNumber,
  orderDate,
  status,
  trackingId,
  totalPrice
}
