import 'package:member_app_v2/common/utils/num_utils.dart';

/// id : 207385
/// type_details : {"id":2,"name":"Regular","key":"REGULAR"}
/// title_details : {"id":9,"name":"Mrs","key":"MRS"}
/// gender_details : {"id":2,"name":"Female","key":"FEMALE"}
/// race_details : {"id":1,"name":"Malay","key":"MALAY"}
/// group : ""
/// first_name : "ALIA flutter: HANUM"
/// last_name : "SHAMSULBAHRI"
/// mobile_number : "60102314530"
/// email : "aliahanum1995@gmail.com"
/// address_line_1 : "SUNGAI SEKAMAT"
/// address_line_2 : ""
/// city : ""
/// area_code : ""
/// date_of_birth : "1995-06-17"
/// total_orders : 0
/// spent_till_now : 438.5
/// last_purchase_date : "2023-03-13 flutter: 02:20:09"
/// company_name : ""
/// company_registration_number : ""
/// company_tax_number : ""
/// company_phone : ""
/// notes : "generated by qrcode"
/// photo_url : "https://retail.ariani.my/storage/892/image_cropper_1680506296603.jpg"
/// available_loyalty_points : 538
/// membership_id : 1
/// registered_at : "2023-03-09 14:34:35"
/// card_number : "Q5369960PZGU"
/// store : "HOUSE OF ARIANI"
/// membership : "NORMAL flutter: MEMBER"
/// ios_digital_pass_link : "https://retail.ariani.my/download-digital-pass/0ed2da5d-f584-11ed-ab86-02001700128e/ios"
/// android_digital_pass_link : "https://retail.ariani.my/download-digital-pass/0ed2da5d-f584-11ed-ab86-02001700128e/android"
/// company : {"id":1,"name":"ARIANI TEXTILES & MANUFACTURING (M) SDN. flutter: BHD.","code":"AR"}

class MemberDetails {
  MemberDetails({
    this.id,
    this.typeDetails,
    this.titleDetails,
    this.genderDetails,
    this.raceDetails,
    this.group,
    this.firstName,
    this.lastName,
    this.mobileNumber,
    this.email,
    this.addressLine1,
    this.addressLine2,
    this.city,
    this.areaCode,
    this.dateOfBirth,
    this.totalOrders,
    this.spentTillNow,
    this.lastPurchaseDate,
    this.companyName,
    this.companyRegistrationNumber,
    this.companyTaxNumber,
    this.companyPhone,
    this.notes,
    this.photoUrl,
    this.availableLoyaltyPoints,
    this.membershipId,
    this.registeredAt,
    this.cardNumber,
    this.store,
    this.membership,
    this.iosDigitalPassLink,
    this.androidDigitalPassLink,
    this.company,
  });

  MemberDetails.fromJson(dynamic json) {
    id = json['id'];
    typeDetails = json['type_details'] != null
        ? TypeDetails.fromJson(json['type_details'])
        : null;
    titleDetails = json['title_details'] != null
        ? TitleDetails.fromJson(json['title_details'])
        : null;
    genderDetails = json['gender_details'] != null
        ? GenderDetails.fromJson(json['gender_details'])
        : null;
    raceDetails = json['race_details'] != null
        ? RaceDetails.fromJson(json['race_details'])
        : null;
    group = json['group'].toString();
    firstName = json['first_name'];
    lastName = json['last_name'];
    mobileNumber = json['mobile_number'];
    email = json['email'];
    addressLine1 = json['address_line_1'];
    addressLine2 = json['address_line_2'];
    city = json['city'];
    areaCode = json['area_code'].toString();
    dateOfBirth = json['date_of_birth'];
    totalOrders = customRound(json['total_orders']);
    spentTillNow = customRound(json['spent_till_now']);
    lastPurchaseDate = json['last_purchase_date'];
    companyName = json['company_name'];
    companyRegistrationNumber = json['company_registration_number'].toString();
    companyTaxNumber = json['company_tax_number'].toString();
    companyPhone = json['company_phone'];
    notes = json['notes'];
    photoUrl = json['photo_url'];
    availableLoyaltyPoints = customRound(json['available_loyalty_points']);
    membershipId = json['membership_id'];
    registeredAt = json['registered_at'];
    cardNumber = json['card_number'];
    store = json['store'];
    membership = json['membership'];
    iosDigitalPassLink = json['ios_digital_pass_link'];
    androidDigitalPassLink = json['android_digital_pass_link'];
    company =
        json['company'] != null ? Company.fromJson(json['company']) : null;
  }
  int? id;
  TypeDetails? typeDetails;
  TitleDetails? titleDetails;
  GenderDetails? genderDetails;
  RaceDetails? raceDetails;
  String? group;
  String? firstName;
  String? lastName;
  String? mobileNumber;
  String? email;
  String? addressLine1;
  String? addressLine2;
  String? city;
  String? areaCode;
  String? dateOfBirth;
  double? totalOrders;
  double? spentTillNow;
  String? lastPurchaseDate;
  String? companyName;
  String? companyRegistrationNumber;
  String? companyTaxNumber;
  String? companyPhone;
  String? notes;
  String? photoUrl;
  double? availableLoyaltyPoints;
  int? membershipId;
  String? registeredAt;
  String? cardNumber;
  String? store;
  String? membership;
  String? iosDigitalPassLink;
  String? androidDigitalPassLink;
  Company? company;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (typeDetails != null) {
      map['type_details'] = typeDetails?.toJson();
    }
    if (titleDetails != null) {
      map['title_details'] = titleDetails?.toJson();
    }
    if (genderDetails != null) {
      map['gender_details'] = genderDetails?.toJson();
    }
    if (raceDetails != null) {
      map['race_details'] = raceDetails?.toJson();
    }
    map['group'] = group;
    map['first_name'] = firstName;
    map['last_name'] = lastName;
    map['mobile_number'] = mobileNumber;
    map['email'] = email;
    map['address_line_1'] = addressLine1;
    map['address_line_2'] = addressLine2;
    map['city'] = city;
    map['area_code'] = areaCode;
    map['date_of_birth'] = dateOfBirth;
    map['total_orders'] = totalOrders;
    map['spent_till_now'] = spentTillNow;
    map['last_purchase_date'] = lastPurchaseDate;
    map['company_name'] = companyName;
    map['company_registration_number'] = companyRegistrationNumber;
    map['company_tax_number'] = companyTaxNumber;
    map['company_phone'] = companyPhone;
    map['notes'] = notes;
    map['photo_url'] = photoUrl;
    map['available_loyalty_points'] = availableLoyaltyPoints;
    map['membership_id'] = membershipId;
    map['registered_at'] = registeredAt;
    map['card_number'] = cardNumber;
    map['store'] = store;
    map['membership'] = membership;
    map['ios_digital_pass_link'] = iosDigitalPassLink;
    map['android_digital_pass_link'] = androidDigitalPassLink;
    if (company != null) {
      map['company'] = company?.toJson();
    }
    return map;
  }
}

/// id : 1
/// name : "ARIANI TEXTILES & MANUFACTURING (M) SDN. flutter: BHD."
/// code : "AR"

class Company {
  Company({
    this.id,
    this.name,
    this.code,
  });

  Company.fromJson(dynamic json) {
    id = json['id'];
    name = json['name'];
    code = json['code'];
  }
  int? id;
  String? name;
  String? code;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['code'] = code;
    return map;
  }
}

/// id : 1
/// name : "Malay"
/// key : "MALAY"

class RaceDetails {
  RaceDetails({
    this.id,
    this.name,
    this.key,
  });

  RaceDetails.fromJson(dynamic json) {
    id = json['id'];
    name = json['name'];
    key = json['key'];
  }
  int? id;
  String? name;
  String? key;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['key'] = key;
    return map;
  }
}

/// id : 2
/// name : "Female"
/// key : "FEMALE"

class GenderDetails {
  GenderDetails({
    this.id,
    this.name,
    this.key,
  });

  GenderDetails.fromJson(dynamic json) {
    id = json['id'];
    name = json['name'];
    key = json['key'];
  }
  int? id;
  String? name;
  String? key;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['key'] = key;
    return map;
  }
}

/// id : 9
/// name : "Mrs"
/// key : "MRS"

class TitleDetails {
  TitleDetails({
    this.id,
    this.name,
    this.key,
  });

  TitleDetails.fromJson(dynamic json) {
    id = json['id'];
    name = json['name'];
    key = json['key'];
  }
  int? id;
  String? name;
  String? key;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['key'] = key;
    return map;
  }
}

/// id : 2
/// name : "Regular"
/// key : "REGULAR"

class TypeDetails {
  TypeDetails({
    this.id,
    this.name,
    this.key,
  });

  TypeDetails.fromJson(dynamic json) {
    id = json['id'];
    name = json['name'];
    key = json['key'];
  }
  int? id;
  String? name;
  String? key;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['id'] = id;
    map['name'] = name;
    map['key'] = key;
    return map;
  }
}
