import 'package:member_app_v2/modules/home/profile/model/member_details.dart';

/// message : "OTP Verified. You can now enjoy the benefits of ARIANI Membership."
/// token : "40489|wu99OsUU73OfTh8CH3905tAt0KBqYKVcYpCLzc8v"
/// expires_in : true
/// member : {"id":229681,"type_details":"","title_details":"","gender_details":"","race_details":"","first_name":"Partha paul","last_name":"","mobile_number":"60176172385","email":"partha.paul007@gmail.com","address_line_1":"","address_line_2":"","city":"","area_code":"","date_of_birth":"2023-05-02","total_orders":0,"spent_till_now":0,"last_purchase_date":"","company_name":"","company_registration_number":"","company_tax_number":"","company_phone":"","notes":"Generated by QR-code on HOUSE OF ARIANI","photo_url":"","available_loyalty_points":0,"membership_id":"","registered_at":"2023-05-03 13:55:32","card_number":"R0DC1881ULOJ","store":"HOUSE OF ARIANI","membership":"","ios_digital_pass_link":"https://retail.ariani.my/download-digital-pass/0fee4dea-f584-11ed-ab86-02001700128e/ios","android_digital_pass_link":"https://retail.ariani.my/download-digital-pass/0fee4dea-f584-11ed-ab86-02001700128e/android","company":{"id":1,"name":"ARIANI TEXTILES & MANUFACTURING (M) SDN. BHD.","code":"AR"}}

class LoginMobileNumberOtpScreenResponse {
  LoginMobileNumberOtpScreenResponse({
    this.message,
    this.token,
    this.refreshToken,
    this.expiresIn,
    this.member,
  });

  LoginMobileNumberOtpScreenResponse.fromJson(dynamic json) {
    message = json['message'].toString();
    token = json['access_token'];
    refreshToken = json['refresh_token'];
    expiresIn = json['expires_in'].toString();
    member =
        json['member'] != null ? MemberDetails.fromJson(json['member']) : null;
  }

  String? message;
  String? token;
  String? refreshToken;
  String? expiresIn;
  MemberDetails? member;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['message'] = message;
    map['access_token'] = token;
    map['refresh_token'] = refreshToken;
    map['expires_in'] = expiresIn;
    if (member != null) {
      map['member'] = member?.toJson();
    }
    return map;
  }
}
